version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-247-161-208.eu-west-1.compute.amazonaws.com
            database: d7s7bs9nv84ap6
            user: vagmavbvketghw
            password: 505e4b99978d0f6d2842594d09daecb06e2937881a2ce02e4ed6defbcb62a4d0
            rawAccess: true
            port: '5432'
            migrations: true
            ssl: true
